/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgetplanner;

/**
 *
 * @author tech city
 */
public class finale extends javax.swing.JFrame {

    /**
     * Creates new form finale
     */
    public finale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sav1 = new javax.swing.JTextField();
        sav3 = new javax.swing.JTextField();
        sav2 = new javax.swing.JTextField();
        sav4 = new javax.swing.JTextField();
        sav5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        savf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        savy = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        savr = new javax.swing.JTextField();
        totin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        savsum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Savings :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gold :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 30));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bank : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, 40));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Share Market :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bonds :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Others :");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, 40));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButton1.setText("Next..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, 130, 40));

        sav1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sav1.setText("0");
        sav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sav1ActionPerformed(evt);
            }
        });
        jPanel1.add(sav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 160, 30));

        sav3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sav3.setText("0");
        jPanel1.add(sav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 160, 30));

        sav2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sav2.setText("0");
        jPanel1.add(sav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 30));

        sav4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sav4.setText("0");
        jPanel1.add(sav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 160, 30));

        sav5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sav5.setText("0");
        jPanel1.add(sav5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 160, 30));

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        savf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jPanel1.add(savf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 220, 40));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Your Savings :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 40));

        savy.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jPanel1.add(savy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 190, 40));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Recommended Savings :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        savr.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jPanel1.add(savr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 190, 40));

        totin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        totin.setToolTipText("");
        jPanel1.add(totin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 180, 40));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total Income");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, 40));

        savsum.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel1.add(savsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 980, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String savi1=sav1.getText();
        int sav1 = Integer.parseInt(savi1);

        String savi2=sav2.getText();
        int sav2 = Integer.parseInt(savi2);

        String savi3=sav3.getText();
        int sav3 = Integer.parseInt(savi3);

        String savi4=sav4.getText();
        int sav4 = Integer.parseInt(savi4);

        String savi5=sav5.getText();
        int sav5 = Integer.parseInt(savi5);

        double total;

        total = sav1+sav2+sav3+sav4+sav5;

        String totale = String.valueOf(total);
        savf.setText(totale);
        savy.setText(totale);
        
        String savre = savr.getText();
        double sav;
        sav  = Double.parseDouble(savre);
        if(total == sav ){
            savsum.setText("Your savings is good!!\nCarry on");
        }
        else if(total > sav){
             savsum.setText("Your savings is fabulous!!\n Best wishes");
        }
        else{
             savsum.setText("You should concentrate on your savings");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sav1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sav1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        next n = new next();
        n.setVisible(true);
        
           
        String pertot = totin.getText();
        n.totin.setText(pertot);
        int pertotal = Integer.parseInt(pertot);
        double pertra = 0.09*pertotal;
        String pertravel = String.valueOf(pertra);
        n.travr.setText(pertravel);
        
        
        double peredu = 0.15*pertotal;
        String pereduc =  String.valueOf(peredu);
        n.edur.setText(pereduc);
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField sav1;
    public static javax.swing.JTextField sav2;
    public static javax.swing.JTextField sav3;
    public static javax.swing.JTextField sav4;
    public static javax.swing.JTextField sav5;
    public javax.swing.JTextField savf;
    public static javax.swing.JTextField savr;
    private javax.swing.JTextField savsum;
    private javax.swing.JTextField savy;
    public static javax.swing.JTextField totin;
    // End of variables declaration//GEN-END:variables
}
